[pytest]
markers =
    ui: marks tests as ui tests
    api: marks tests as api tests
    smoke: marks tests as smoke tests
    regression: marks tests as regression tests

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v -s --tb=short --strict-markers